### ISSUE TITLE
num4ssp in paired-end mode

### ISSUE THREAD

**Issue by avilella** [rnakato/SSP#1]
Hi,

The documentation says:

```
In default, FCS is calcutated for 10M nonredundant reads. If the number of nonredundant reads in the input data are smaller than 10M, specify smaller number for fair comparison among samples as follows:

 ssp -i ChIP1.bam -o ChIP --gt genometable.txt --num4ssp 5000000
```

If my data is paired, should I add the parameter of the number of reads or the number of read pairs?

**Comment by rnakato** [comment]
Hi, 
Thank you for trying SSP. For paired-end samples, SSP considers the number of read pairs. The counted number is shown in *.stats.txt in sspout directory.
And I found a bug for --pair option, so please update to SSP version 1.0.1 (now latest) for paired-end samples.

**Comment by avilella** [comment]
Thanks. Updated now. I'll divide the number of reads by 2 in `--pair` mode when giving the `--num4ssp $val` parameter.

One more question: for bam files with more than 10M reads/read pairs, is it better to still supply the parameter or use default without parameter?

**Comment by rnakato** [comment]
When all samples to be compared have more than 10M reads/read pairs, it is not necessary to supply `--num4ssp` option. When not all samples, supply `--num4ssp` option to all samples.

**Comment by avilella** [comment]
Brilliant, thanks.
