### ISSUE TITLE
SSP not working (Segmentation fault)

### ISSUE THREAD

**Issue by julenmendieta** [rnakato/SSP#2]
Hi, 
I have installed SSP in 3 different computers (Ubuntu 20.04.3, CentOS 7, and MacOS Monterrey 12.3.1), but I couldn't successfully run it on my bam or sam files, I always got a segmentation fault error. I have also tried it on CentOS 7 (an HPC) with the singularity image, but it finishes after a few seconds without an output message.

My bam files are sorted and indexed and contain paired-end reads. Until now, I have used them with other programs with no issues. Do you know where might be the issue?
Many thanks!

**Comment by rnakato** [comment]
Hi julenmendieta, can you show the command you executed? What NGS assay do you use?

**Comment by julenmendieta** [comment]
Hi,

These are two of the simplest commands I tried:
ssp -i out.bam -o lala_ --pair -f BAM --gt ${genomeTable} -p 8
ssp -i out.sam -o lala_ --pair --gt ${genomeTable} -p 8

I also tried with
singularity exec [PATH]/ssp_drompa.img ssp
and without the "-p" and "--pair" options

The sorted and indexed BAM files come from pair-end ChIP-seq experiments and have been processed similarly to here:
https://github.com/nf-core/chipseq

Cheers,
J

**Comment by rnakato** [comment]
Sorry for your inconvenience. I guess the error is caused by the genome_table file you specified.
Do you use the latest version of SSP (v1.2.4)? I fixed a bug related to the error (see Changelog v1.2.4 https://github.com/rnakato/SSP/blob/master/ChangeLog.md).
If the problem is not solved, I'll check the bug in my environment. Can you show me the genome_table file?

**Comment by julenmendieta** [comment]
Hi rnakato, sorry for the delayed answer. 
Given your comment about the genome_table file, I took a look at it and saw that the issue is caused when the chromosome and size are separated by spaces instead of tabs. I had installed SPP v1.2.4 and now that I have converted the spaces to tabs it seems to be running well. Sorry for the inconvenience, this is kind of the first thing that I usually check when having issues with a program, but I missed it this time

**Comment by rnakato** [comment]
I'm glad the problem was solved. I'll add the error message when the format of a  genome_table file is wrong.

**Comment by julenmendieta** [comment]
Hi,

These are two of the simplest commands I tried:

> ssp -i out.bam -o lala_ --pair -f BAM --gt ${genomeTable} -p 8
> ssp -i out.sam -o lala_ --pair --gt ${genomeTable} -p 8


I also tried with

> singularity exec [PATH]/ssp_drompa.img ssp

and without the "-p" and "--pair" options

The sorted and indexed BAM files come from pair-end ChIP-seq experiments
and have been processed similarly to here:
https://github.com/nf-core/chipseq

Cheers,
J
