### ISSUE TITLE
please provide release tag

### ISSUE THREAD

**Issue by EricDeveaud** [rnakato/SSP#5]
Hello, 

I was asked to install SSP on our cluster, our policy is to install release tag versions in order to provide some reproducibility among the time.
can you provide such release tag.

thanks

regards

Eric

**Comment by rnakato** [comment]
Now I created a first release tag (SSP version 1.1.0). Is it fine with you?

**Comment by EricDeveaud** [comment]
thanks

**Comment by EricDeveaud** [comment]
now installed 
thanks
