### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by AlexBlais74** [rnakato/SSP#7]
Hello
I am trying to install the latest version of SSP, and I am facing a problem with make. The last few lines of text in the terminal are copied below. I am happy to post more info if needed. Can you help me with this?
I use a large computing cluster, and the 'make' command is issued after loading the following modules
module load nixpkgs/16.09  intel/2018.3 gcc/7.3.0
module load boost/1.68.0 samtools/1.9 gsl/2.5 r/3.6.0 clang/3.9.0

I should specify that I was able to use SSP 1.1.1 without problem. I suppose my troubles come from the use of the different compiler?
Thanks in advance for your help
Alex

/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/boost/1.68.0/lib/libboost_program_options.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/boost/1.68.0/lib/libboost_thread.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/boost/1.68.0/lib/libboost_program_options.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/boost/1.68.0/lib/libboost_program_options.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:35: bin/ssp] Error 1

**Comment by rnakato** [comment]
It the OS system of the cluster CentOS7? The error message looks like the failure of access to the standard compiler library std from Boost. However, the library environment of your system seems strictly fixed, so it might be difficult to solve this problem in a straightforward way.
Similar issue: https://stackoverflow.com/questions/42892279/caffe-installation-issue

I recommend either of the two practical solutions below:
- Change "clang++" to "g++" in ``Makefile`` and check if the compilation works well.
- Downgrade SSP version to 1.1.1. Actually the output of SSP is the same.

**Comment by AlexBlais74** [comment]
Thank you for the suggestion. Since the output hasn't changed, I reverted to using v1.1.5 and the installation went fine.
Alex
